Update deploy-aws-app-runner.yml

diff --git a/.github/workflows/deploy-aws-app-runner.yml b/.github/workflows/deploy-aws-app-runner.yml
--- a/.github/workflows/deploy-aws-app-runner.yml
+++ b/.github/workflows/deploy-aws-app-runner.yml
@@ -31,6 +31,16 @@ jobs:
       group: deploy-${{ inputs.environment }}
       cancel-in-progress: false
     steps:
+      - name: Check if secrets are available
+        run: |
+           if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
+             echo "AWS_ACCESS_KEY_ID is missing"
+             exit 1
+           fi
+             if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
+               echo "AWS_SECRET_ACCESS_KEY is missing"
+               exit 1
+             fi      
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
